### ISSUE TITLE
Library domain has been moved

### ISSUE THREAD

**Issue by abhinandanudupa** [shaansubbaiah/bmsce-paper-ripper#3]
The Library URL has been moved from [http://103.40.80.24:8080](http://103.40.80.24:8080) to [http://10.40.4.17:8080](http://10.40.4.17:8080) - taken from [reference](https://bmsce.ac.in/home/Library-TechFocuz-Digital-Library-Software)

But unfortunately, the the new address is a private one : (

**Comment by shaansubbaiah** [comment]
`10 . 40 . 4 . 17` is the internal address, `103 . 40 . 80 . 24` is the address to access the site externally. Either the site is down temporarily or they've disabled it due to excessive traffic :skull: 

Someone _may_ run the script while connected to the internal network and create a mirror of all the papers.

**Comment by abhinandanudupa** [comment]
> `10 . 40 . 4 . 17` is the internal address, `103 . 40 . 80 . 24` is the address to access the site externally. Either the site is down temporarily or they've disabled it due to excessive traffic skull

Oh my bad.

**Comment by abhinandanudupa** [comment]
But how did you find the external address?

Where was it?

**Comment by shaansubbaiah** [comment]
> But how did you find the external address?
> 
> Where was it?

It was in one of the circular/ mails

**Comment by abhinandanudupa** [comment]
Ok, thank you

**Comment by abhinandanudupa** [comment]
Hey!
This is the wrong place to ask about this but can you  tell me about the application process for GSoC - what helped to get selected and which projects to choose?
